// Ljuska u novoj paleti: pretraga (Ctrl+K), obaveštenja, meni na telefonu, skupljena šina
const path = require('path');
const { chromium } = (() => { try { return require('playwright'); } catch (e) { return require(process.env.PLAYWRIGHT_DIR || 'D:/MANGEMENT-APP-MAIN/preprod/e2e/node_modules/playwright'); } })();
const OUT = path.join(__dirname, 'snimci');
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, storageState: path.join(__dirname, 'auth.json') });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('http://localhost:3300/security/objekti');
  await page.waitForSelector('[data-testid="facility-card"]');
  await page.waitForTimeout(1200);
  await page.keyboard.press('Control+k');
  await page.waitForSelector('[data-testid="palette"]');
  await page.fill('[data-testid="palette-input"]', 'au');
  await page.waitForTimeout(600);
  await page.screenshot({ path: path.join(OUT, 'x-pretraga.png') });
  await page.keyboard.press('Escape');
  await page.waitForTimeout(400);
  await page.click('.sx-rail [data-testid="bell"]');
  await page.waitForSelector('[data-testid="notifications"]');
  await page.waitForTimeout(600);
  await page.screenshot({ path: path.join(OUT, 'x-obavestenja.png') });
  await page.keyboard.press('Escape');
  await page.waitForTimeout(300);
  await page.click('.sx-rail__collapse');
  await page.waitForTimeout(800);
  await page.screenshot({ path: path.join(OUT, 'x-sina-skupljena.png') });
  await page.click('.sx-rail__markbtn');
  await page.waitForTimeout(700);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://localhost:3300/security/objekti');
  await page.waitForSelector('[data-testid="menu-button"]');
  await page.click('[data-testid="menu-button"]');
  await page.waitForSelector('[data-testid="mobile-menu"]');
  await page.waitForTimeout(900);
  await page.screenshot({ path: path.join(OUT, 'x-meni-telefon.png') });
  console.log('greške:', errors.length ? errors : 'nema');
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
